# Generated by Django 5.1.1 on 2025-04-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_alter_post_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posts_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
